CREATE TABLE Familia (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Nom NVARCHAR(20) NOT NULL,
    Descripcio NVARCHAR(MAX)
);

CREATE TABLE Producte (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    CODI CHAR(8) NOT NULL,
    Descripcio NVARCHAR(MAX),
    Preu DECIMAL(10, 2),
    Descompte DECIMAL(10, 2),
    tipus INT,
    id_tipus UNIQUEIDENTIFIER,
    FOREIGN KEY(id_tipus) REFERENCES Familia(ID)
);

CREATE TABLE CarritoCompra (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    nom VARCHAR(10) NOT NULL
);

CREATE TABLE CarritoProducte (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    ID_CARR UNIQUEIDENTIFIER,
    ID_PROD UNIQUEIDENTIFIER,
    Quantitat INT NOT NULL,
    FOREIGN KEY(ID_CARR) REFERENCES CarritoCompra(ID),
    FOREIGN KEY(ID_PROD) REFERENCES Producte(ID)
);
